export const ACTION_TYPE = {
    SET_CART_DATA: "SET_CART_DATA",
    SET_WISHLIST_DATA: "SET_WISHLIST_DATA",
    SET_LOGGED_IN_PROFILE: "SET_LOGGED_IN_PROFILE",
    SET_SHIPPING_ADDRESS_DATA: "SET_SHIPPING_ADDRESS_DATA",
    SET_CUSTOMER_ORDERS_DATA: "SET_CUSTOMER_ORDERS_DATA",
};